// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/account": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Помечает аккаунт как удалённый (soft delete, grace period 7\nдней). Требует подтверждения: паролем (если он установлен)\nлибо magic-link кодом, полученным через\n/account/delete/request-confirmation (для oauth-only\nпользователей без пароля). Все refresh-токены и активные\nсессии немедленно отзываются. Идемпотентно — повторный вызов\nна уже удалённый аккаунт не является ошибкой.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Удалить аккаунт",
                "parameters": [
                    {
                        "description": "Пароль ИЛИ session_id+code",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_account_delete.Request"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Аккаунт удалён"
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Access token отсутствует/невалиден, либо неверный пароль/код подтверждения",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Превышен лимит запросов",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/account/delete/request-confirmation": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отправляет magic-link код на email текущего пользователя для\nподтверждения удаления аккаунта. Требуется только для\noauth-only пользователей без пароля — у них нет иного\nспособа подтвердить чувствительное действие. Возвращает\nsession_id, который затем передаётся вместе с кодом из письма\nв /account/delete.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Запросить подтверждение удаления аккаунта через magic link",
                "responses": {
                    "200": {
                        "description": "Код отправлен на email",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_id": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Access token отсутствует, невалиден или истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/account/restore": {
            "post": {
                "description": "Отменяет soft-delete, если grace period (7 дней) ещё не\nистёк, и сразу выдаёт access/refresh токены. Требует\nподтверждения: паролем (если он установлен) либо\nmagic-link токеном, полученным через\n/account/restore/request-confirmation (для oauth-only\nпользователей без пароля). Неаутентифицированный эндпоинт.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Восстановить удалённый аккаунт",
                "parameters": [
                    {
                        "description": "Email + (пароль ИЛИ session_id+token) + app_id",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_account_restore.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Аккаунт восстановлен, выданы токены",
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_account_restore.Response"
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Неверный пароль или код подтверждения, аккаунт не найден, не был удалён или grace period истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Превышен лимит запросов",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/account/restore/request-confirmation": {
            "post": {
                "description": "Отправляет magic-link код на email указанного (soft-deleted)\nаккаунта для подтверждения восстановления. Неаутентифицированный\nэндпоинт — юзер не может залогиниться, пока аккаунт удалён.\nВозвращает session_id для последующего запроса в /account/restore.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "account"
                ],
                "summary": "Запросить подтверждение восстановления аккаунта через magic link",
                "parameters": [
                    {
                        "description": "Email и app_id",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_account_request_restore_confirmation.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Код отправлен на email",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_id": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Невалидный запрос",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Превышен лимит запросов",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/2fa/disable/request-confirmation": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отправляет magic-link код на email текущего пользователя для\nподтверждения отключения 2FA. Требуется только для\noauth-only пользователей без пароля — у них нет иного\nспособа подтвердить чувствительное действие. Возвращает\nsession_id, который затем передаётся вместе с кодом из письма\nв /auth/2fa/disable.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2fa"
                ],
                "summary": "Запросить подтверждение отключения 2FA через magic link",
                "responses": {
                    "200": {
                        "description": "Код отправлен на email",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_id": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Access token отсутствует, невалиден или истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/2fa/magic-link/disable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Отключает magic-link 2FA. Подтверждение зависит от того, есть\nли у пользователя пароль: если да — передаётся password; если\nнет (oauth-only аккаунт) — передаются session_id и token,\nполученные через /auth/2fa/magic-link/request-action-confirmation.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2fa"
                ],
                "summary": "Отключить magic-link 2FA",
                "parameters": [
                    {
                        "description": "Подтверждение отключения (один из наборов полей)",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                },
                                "session_id": {
                                    "type": "string"
                                },
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "2FA отключена",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Access token отсутствует, невалиден или истёк, либо неверное подтверждение (пароль/magic-link код)",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "2FA не включена",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/2fa/magic-link/enable": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Включает magic-link 2FA для текущего пользователя. Требует,\nчтобы у пользователя уже был рабочий фактор для будущего\nотключения (пароль или хотя бы один привязанный oauth-аккаунт) —\nиначе включение необратимо заблокирует доступ к аккаунту.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2fa"
                ],
                "summary": "Включить magic-link 2FA",
                "responses": {
                    "200": {
                        "description": "2FA включена",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Access token отсутствует, невалиден или истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "2FA уже включена, либо нет ни одного доступного фактора для будущего disable",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/2fa/magic-link/resend": {
            "post": {
                "description": "Инвалидирует предыдущую активную ссылку и высылает новую в\nрамках той же pending-сессии, начатой на /auth/login. Не\nподтверждает и не раскрывает факт доставки письма — ответ\nодинаковый независимо от того, дошло письмо или нет.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2fa"
                ],
                "summary": "Повторно отправить magic-link",
                "parameters": [
                    {
                        "description": "Идентификатор pending-сессии",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_id": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новая ссылка отправлена (либо попытка предпринята)",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Невалидное тело запроса",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Pending-сессия не найдена или истекла — нужно начать логин заново",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Слишком частые запросы на повторную отправку",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/2fa/magic-link/verify": {
            "post": {
                "description": "Завершает второй фактор аутентификации: проверяет токен из\nписьма в связке с session_id, полученным на этапе /auth/login,\nи при успехе выдаёт access/refresh токены. Токен одноразовый —\nповторное использование того же токена или session_id отклоняется.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2fa"
                ],
                "summary": "Подтверждение magic-link 2FA",
                "parameters": [
                    {
                        "description": "Данные для подтверждения",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_id": {
                                    "type": "string"
                                },
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "2FA подтверждена, выданы токены",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {
                                    "type": "string"
                                },
                                "refresh_token": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Невалидное тело запроса или ошибка валидации",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Токен невалиден, истёк, уже использован, либо сессия истекла",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "## Описание\nВыполняет аутентификацию пользователя по email и паролю. Если\nу пользователя включена magic-link 2FA, вместо токенов\nвозвращается session_id для подтверждения через\n/auth/2fa/magic-link/verify; access/refresh в этом случае не выдаются.\n\n### Процесс аутентификации:\n1. Валидация входных данных (email формат, наличие пароля)\n2. Проверка существования пользователя в базе данных\n3. Верификация пароля (bcrypt hash comparison)\n4. Проверка статуса email (должен быть подтвержден)\n5. Валидация app_id (приложение должно существовать)\n6. Проверка статуса 2FA:\n- если выключена — генерация JWT токенов (access и refresh)\n- если включена — создание pending-сессии, отправка magic link на email, возврат session_id без токенов\n\n### Токены:\n- **Access Token**: JWT токен для доступа к защищенным ресурсам (TTL: 15 минут)\n- **Refresh Token**: JWT токен для обновления access токена (TTL: 30 дней)\n- **Session ID** (при включённой 2FA): используется для подтверждения через /auth/2fa/magic-link/verify, не является токеном доступа\n\n### Коды ошибок:\n- ` + "`" + `400` + "`" + ` - Некорректные данные (невалидный email, отсутствие полей, невалидный app_id)\n- ` + "`" + `401` + "`" + ` - Неверные credentials (пароль не совпадает; используется и для несуществующего email — не различается намеренно, во избежание user enumeration)\n- ` + "`" + `403` + "`" + ` - Email не подтвержден\n- ` + "`" + `500` + "`" + ` - Внутренняя ошибка сервера",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Аутентификация пользователя",
                "parameters": [
                    {
                        "description": "Данные для входа",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "app_id": {
                                    "type": "integer"
                                },
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пароль верен, требуется подтверждение magic-link 2FA",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "session_id": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                },
                                "two_factor_pending": {
                                    "type": "boolean"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или невалидный app_id",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Неверные credentials",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Email не подтвержден",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "x-order": 1
            }
        },
        "/auth/logout": {
            "post": {
                "description": "## Описание\nЗавершает активную сессию пользователя, инвалидируя refresh токен.\n\n### Процесс выхода:\n1. Валидация refresh токена из тела запроса\n2. Проверка существования токена в базе данных\n3. Добавление токена в blacklist (Redis)\n4. Удаление токена из таблицы активных сессий\n5. Инвалидация связанного access токена\n\n### Особенности:\n- После logout refresh токен больше нельзя использовать для получения новых access токенов\n- Access токен технически остается валидным до истечения TTL (~15 минут)\n- Для немедленной инвалидации access токена используется blacklist в Redis\n- Поддержка \"logout from all devices\" (опционально)\n\n### Безопасность:\n- Токен в blacklist хранится только до истечения его TTL\n- При попытке использовать инвалидированный токен возвращается 401\n- Логирование всех операций logout для аудита",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из системы",
                "parameters": [
                    {
                        "description": "Refresh токен для инвалидации",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный выход из системы",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации: токен не передан или некорректный JSON",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Невалидный или истекший refresh токен",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "x-order": 4
            }
        },
        "/auth/oauth/accounts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает все OAuth-провайдеры, привязанные к аккаунту\nтекущего аутентифицированного пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Список привязанных OAuth-аккаунтов",
                "responses": {
                    "200": {
                        "description": "Список привязанных аккаунтов",
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_oauth_accounts.Response"
                        }
                    },
                    "401": {
                        "description": "Access token отсутствует, невалиден или истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/oauth/{provider}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Удаляет связь между указанным OAuth-провайдером и аккаунтом\nтекущего аутентифицированного пользователя.\nЕсли этот способ входа является последним доступным методом\nаутентификации, операция будет отклонена, чтобы предотвратить\nпотерю доступа к аккаунту.",
                "tags": [
                    "oauth"
                ],
                "summary": "Отвязка OAuth-провайдера от аккаунта",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название OAuth-провайдера (например: google, github)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "OAuth-провайдер успешно отвязан"
                    },
                    "401": {
                        "description": "Access-токен отсутствует, недействителен или истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Нельзя отвязать последний доступный способ аутентификации",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "У пользователя отсутствует привязка к указанному OAuth-провайдеру",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/oauth/{provider}/callback": {
            "get": {
                "description": "Обрабатывает перенаправление от OAuth-провайдера после того, как пользователь предоставил или отклонил доступ.\nПроверяет параметр state на соответствие ранее сохранённому значению (авторизация или привязка аккаунта),\nобменивает код авторизации на токены провайдера и в зависимости от типа операции\nлибо выдает новую пару access и refresh токенов,\nлибо привязывает OAuth-провайдера к существующему аккаунту.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Callback OAuth-провайдера",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название OAuth-провайдера (например: google, github)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Код авторизации, полученный от OAuth-провайдера",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Токен состояния (state), должен совпадать со значением, выданным при начале авторизации или привязки аккаунта",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Код ошибки, возвращаемый OAuth-провайдером, если пользователь отказал в доступе",
                        "name": "error",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация или привязка аккаунта",
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_oauth_callback.Response"
                        }
                    },
                    "400": {
                        "description": "Пользователь отказал в доступе, отсутствуют параметры code/state, указан некорректный app_id либо state недействителен или истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "403": {
                        "description": "Email, полученный от OAuth-провайдера, не подтверждён",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Указанный OAuth-провайдер не поддерживается",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Конфликт данных: аккаунт с таким email уже существует либо OAuth-провайдер уже привязан к другому аккаунту",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/oauth/{provider}/link": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Запускает OAuth2-процесс привязки стороннего OAuth-провайдера к аккаунту\nтекущего аутентифицированного пользователя.\nТребует действительный access-токен. Идентификатор пользователя\nизвлекается из его данных, а не из параметров запроса,\nпоэтому привязка всегда выполняется для текущей сессии.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Привязка OAuth-провайдера к существующему аккаунту",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название OAuth-провайдера (например: google, github)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "URL, на который будет выполнено перенаправление после завершения авторизации. Должен входить в список разрешённых адресов.",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ссылка для перехода к OAuth-провайдеру",
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_oauth_link.Response"
                        }
                    },
                    "400": {
                        "description": "Некорректный redirect_uri или app_id",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Access-токен отсутствует, недействителен или истёк",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "OAuth-провайдер не поддерживается",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/oauth/{provider}/login": {
            "get": {
                "description": "Запускает процесс OAuth2-авторизации для указанного OAuth-провайдера.\nПроверяет корректность app_id и redirect_uri, а также соответствие\nredirect_uri списку разрешённых адресов.\nПосле успешной проверки формирует параметр state и перенаправляет\nпользователя на страницу авторизации OAuth-провайдера.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "oauth"
                ],
                "summary": "Начало OAuth-авторизации",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Название OAuth-провайдера (например: google, github)",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Идентификатор клиентского приложения",
                        "name": "app_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "URL для перенаправления после завершения авторизации. Должен входить в список разрешённых адресов.",
                        "name": "redirect_uri",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Перенаправление на страницу авторизации OAuth-провайдера"
                    },
                    "400": {
                        "description": "Некорректный app_id или redirect_uri не прошёл проверку",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "OAuth-провайдер не поддерживается",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Не удалось сформировать URL для авторизации",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/password/forgot": {
            "post": {
                "description": "Запускает процесс сброса пароля для указанного адреса электронной почты.\nНезависимо от того, существует ли аккаунт с указанным email,\nвсегда возвращает ответ с кодом 200, чтобы исключить возможность\nопределения существования аккаунтов.\nЕсли аккаунт существует, на указанный email будет отправлено\nписьмо со ссылкой для сброса пароля. Ошибки отправки письма\nфиксируются на стороне сервера и не влияют на ответ API.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Запрос на сброс пароля",
                "parameters": [
                    {
                        "description": "Адрес электронной почты пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Запрос успешно принят",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса или ошибка валидации",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "429": {
                        "description": "Превышен допустимый лимит запросов",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/password/reset": {
            "post": {
                "description": "Сбрасывает пароль пользователя с использованием токена,\nполученного по электронной почте.\nТокен должен быть передан в теле запроса в формате\n\"selector.verifier\", где selector — UUID, а verifier —\nстрока в формате URL-safe Base64.\nТокен можно использовать только один раз. После успешного\nсброса пароля он становится недействительным.\nНовый пароль должен содержать не менее 8 символов и\nотличаться от текущего пароля.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Сброс пароля",
                "parameters": [
                    {
                        "description": "Токен для сброса пароля и новый пароль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "password": {
                                    "type": "string"
                                },
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пароль успешно сброшен",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Некорректный формат токена, токен недействителен, истёк или уже был использован, пароль не соответствует требованиям либо совпадает с текущим",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "## Описание\nОбменивает действующий refresh токен на новую пару токенов (access и refresh).\n\n### Процесс обновления:\n1. Валидация refresh токена (подпись JWT, срок действия)\n2. Извлечение user_id и app_id из payload токена\n3. Проверка что токен не находится в blacklist (Redis)\n4. Проверка статуса пользователя (не заблокирован, email подтвержден)\n5. Генерация новой пары токенов:\n- Новый access токен (TTL: 15 минут)\n- Новый refresh токен (TTL: 30 дней)\n6. Инвалидация старого refresh токена (token rotation)\n7. Сохранение нового refresh токена в БД\n\n### Token Rotation (безопасность):\n- **Каждый refresh токен одноразовый** — после использования старый токен инвалидируется\n- Это защищает от атак с украденными токенами\n- При попытке использовать старый токен — все сессии пользователя инвалидируются\n\n### Время жизни токенов:\n- **Access Token**: 15 минут (короткий для безопасности)\n- **Refresh Token**: 30 дней (удобство для пользователя)\n- Если пользователь неактивен 30 дней — требуется повторный login\n\n### Когда использовать:\n- Access токен истек (получили 401 на защищенном endpoint)\n- Превентивное обновление перед истечением access токена\n- После длительного простоя приложения\n\n### Ошибки:\n- ` + "`" + `400` + "`" + `: Невалидный JSON или отсутствует refresh_token\n- ` + "`" + `401` + "`" + `: Токен истек, невалиден или уже использован\n- ` + "`" + `403` + "`" + `: Пользователь заблокирован\n- ` + "`" + `500` + "`" + `: Ошибка БД или генерации токенов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление access токена",
                "parameters": [
                    {
                        "description": "Текущий refresh токен",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "refresh_token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новая пара токенов",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {
                                    "type": "string"
                                },
                                "refresh_token": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Невалидный или истекший токен",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "x-order": 3
            }
        },
        "/auth/register": {
            "post": {
                "description": "## Описание\nСоздает новую учетную запись пользователя в системе и отправляет письмо с подтверждением email.\n\n### Процесс регистрации:\n1. Валидация входных данных (email формат, наличие username и пароля)\n2. Проверка уникальности email и username в базе данных\n3. Хеширование пароля с использованием bcrypt (cost factor 12)\n4. Создание записи пользователя в БД со статусом ` + "`" + `email_verified = false` + "`" + `\n5. Генерация JWT токена верификации (валиден 24 часа)\n6. Отправка email с ссылкой подтверждения через RabbitMQ\n\n### Требования к данным:\n- **Email**: Валидный email формат (example@domain.com), должен быть уникальным\n- **Username**: Минимум 3 символа, только буквы, цифры и подчеркивание, должен быть уникальным\n- **Password**: Минимум 8 символов, рекомендуется использовать заглавные буквы, цифры и спецсимволы\n\n### Email верификация:\n- Письмо отправляется асинхронно через RabbitMQ (не блокирует ответ)\n- Токен верификации действует 24 часа\n- До подтверждения email пользователь не может войти в систему\n- Неподтвержденные аккаунты автоматически удаляются через 7 дней\n\n### Формат ссылки верификации:\n` + "`" + `http://domain.com/auth/verify?token=eyJhbGc...` + "`" + `",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные нового пользователя",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                },
                                "username": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь успешно создан, письмо отправлено",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                },
                                "user_id": {
                                    "type": "integer"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации: некорректный email, слишком короткий пароль или отсутствуют обязательные поля",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "409": {
                        "description": "Пользователь с таким email или username уже существует",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка: проблемы с БД, RabbitMQ или email сервисом",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "x-order": 2
            }
        },
        "/auth/verify": {
            "get": {
                "description": "## Описание\nПодтверждает email адрес пользователя по токену из письма, активируя учетную запись.\n\n### Процесс верификации:\n1. Извлечение токена из query параметра ` + "`" + `token` + "`" + `\n2. Валидация JWT токена (подпись, срок действия)\n3. Извлечение user_id из payload токена\n4. Проверка что пользователь существует и email еще не подтвержден\n5. Обновление статуса ` + "`" + `email_verified = true` + "`" + ` в базе данных\n6. Инвалидация токена (предотвращение повторного использования)\n\n### Особенности токена:\n- **Срок действия**: 24 часа с момента регистрации\n- **Формат**: JWT (JSON Web Token) подписанный HMAC-SHA256\n- **Одноразовый**: После успешной верификации токен инвалидируется\n- **Payload**: Содержит ` + "`" + `user_id` + "`" + ` и ` + "`" + `exp` + "`" + ` (время истечения)\n\n### После подтверждения:\n- Пользователь может войти в систему через ` + "`" + `/auth/login` + "`" + `\n- Email помечен как подтвержденный навсегда\n- Опционально: отправка welcome email\n\n### Ошибки:\n- ` + "`" + `400` + "`" + `: Токен отсутствует в URL\n- ` + "`" + `401` + "`" + `: Токен невалидный, истек или уже использован\n- ` + "`" + `500` + "`" + `: Ошибка базы данных",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Подтверждение email адреса",
                "parameters": [
                    {
                        "type": "string",
                        "description": "JWT токен верификации из email",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email успешно подтвержден, можно входить в систему",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Токен отсутствует в URL",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Токен невалидный, истек или уже использован",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "x-order": 5
            }
        },
        "/auth/verify/resend": {
            "post": {
                "description": "## Описание\nПовторно отправляет письмо с подтверждением email адреса пользователю.\n\n### Процесс отправки:\n1. Валидация email формата\n2. Проверка существования пользователя с указанным email\n3. Проверка статуса верификации email\n4. Если email не подтвержден - генерация нового токена верификации\n5. Отправка письма через RabbitMQ\n6. Возврат успешного ответа (независимо от статуса верификации)\n\n### Когда использовать:\n- Пользователь не получил первое письмо\n- Токен верификации истек (24 часа)\n- Письмо попало в спам\n- Пользователь случайно удалил письмо\n\n### Безопасность (важно!):\n- Endpoint всегда возвращает 200 OK, даже если email уже подтвержден\n- Это предотвращает enumeration атаки (определение существующих email)\n- Не раскрывает информацию о существовании пользователя\n- Rate limiting должен быть настроен (максимум 3 запроса в час на email)\n\n### Особенности:\n- Если email уже подтвержден - письмо не отправляется (но ответ 200 OK)\n- Новый токен инвалидирует предыдущий\n- Токен действителен 24 часа\n- Отправка асинхронная через RabbitMQ (не блокирует ответ)\n",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Повторная отправка письма верификации",
                "parameters": [
                    {
                        "description": "Email пользователя",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Письмо отправлено (или email уже подтвержден)",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации: некорректный email формат",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "error": {
                                    "type": "string"
                                },
                                "status": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "x-order": 6
            }
        },
        "/health": {
            "get": {
                "description": "Проверяет, запущен ли сервис и готов ли он обрабатывать запросы.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Проверка работоспособности",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_http_server_handlers_infrastructure_health.Response"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "Отдаёт метрики сервиса в формате Prometheus exposition format.\nНе предназначен для вызова из браузера/фронтенда — эндпоинт\nдля scrape'а Prometheus-сервером.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Prometheus метрики",
                "responses": {
                    "200": {
                        "description": "Метрики в текстовом формате Prometheus",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_http_server_handlers_account_delete.Request": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "SecurePass123!"
                },
                "session_id": {
                    "type": "string",
                    "example": "abcDEF123..."
                },
                "token": {
                    "type": "string",
                    "example": "fkajeDJ1p3FJ..."
                }
            }
        },
        "internal_http_server_handlers_account_request_restore_confirmation.Request": {
            "type": "object",
            "required": [
                "app_id",
                "email"
            ],
            "properties": {
                "app_id": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "example@domain.com"
                }
            }
        },
        "internal_http_server_handlers_account_restore.Request": {
            "type": "object",
            "required": [
                "app_id",
                "email"
            ],
            "properties": {
                "app_id": {
                    "type": "integer",
                    "example": 1
                },
                "email": {
                    "type": "string",
                    "example": "example@domain.com"
                },
                "password": {
                    "type": "string",
                    "example": "SecurePass123!"
                },
                "session_id": {
                    "type": "string",
                    "example": "fkajeDJ1p3FJ..."
                },
                "token": {
                    "type": "string",
                    "example": "abcDEF123..."
                }
            }
        },
        "internal_http_server_handlers_account_restore.Response": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "error": {
                    "type": "string",
                    "example": "error"
                },
                "refresh_token": {
                    "type": "string"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_http_server_handlers_infrastructure_health.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_http_server_handlers_oauth_accounts.Account": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-07-24T12:00:00Z"
                },
                "email": {
                    "type": "string",
                    "example": "example@domain.com"
                },
                "provider": {
                    "type": "string",
                    "example": "google"
                }
            }
        },
        "internal_http_server_handlers_oauth_accounts.Response": {
            "type": "object",
            "properties": {
                "accounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_http_server_handlers_oauth_accounts.Account"
                    }
                },
                "error": {
                    "type": "string",
                    "example": "error"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_http_server_handlers_oauth_callback.Response": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "fkajeDJ1p3FJ..."
                },
                "error": {
                    "type": "string",
                    "example": "error"
                },
                "refresh_token": {
                    "type": "string",
                    "example": "abcDEF123..."
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "internal_http_server_handlers_oauth_link.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error"
                },
                "redirect_url": {
                    "type": "string",
                    "example": "https://www.google.com/"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Auth Service API",
	Description:      "Сервис авторизации",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
